name: Dependency Update Check

on:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at midnight
  workflow_dispatch: # Allow manual trigger

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Check for outdated dependencies
      run: |
        npm outdated || true
        echo "::notice title=Dependency Check::Check completed. Review outdated packages above."
        
    - name: Security audit
      run: |
        npm audit --audit-level=moderate || true
        echo "::notice title=Security Audit::Audit completed. Review security issues above."
